### PR TITLE
Add node-casbin redis adapter, README.md

### PR DESCRIPTION
**Pull request by 0xethsign**
Build, tests yet to be added.

### CODE REVIEW

**Comment by hsluoyz** [comment]
@smrpn plz remove merge commits

image

**Comment by 0xethsign** [comment]
Hey, I'm trying to delete those commits, but I don't know how to do that. Can you help?

**Comment by hsluoyz** [comment]
@smrpn no worry, squash-merged :)

**Comment by 0xethsign** [comment]
What should be the next steps here? I checked the [casbin/redis-adapter](https://github.com/casbin/redis-adapter) repo. We need to add CI and tests.

**Comment by hsluoyz** [comment]
@smrpn yeah, add tests, setup CI and code coverage, add badges, etc.

**Pull request merged**
